### ISSUE TITLE
Incorporate automatic link expansion?

### ISSUE THREAD

**Issue by anishathalye** [Detry322/hubot-redisred#1]
Could you add a setting like `HUBOT_REDISRED_PREFIX` and then add a `robot.hear` so that when someone types `$HUBOT_REDISRED_PREFIX/link`, it'll automatically expand to `$HUBOT_REDISRED_URL/link`?

(basically, this is taking the go link feature in hackbot and making it slightly more general, and moving it to hubot-redisred instead of keeping it in the `scripts` directory in hackbot)

**Comment by Detry322** [comment]
v1.1.1
